<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0-android;net10.0-ios</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <RootNamespace>ReciclaMe</RootNamespace>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <MauiXamlInflator>SourceGen</MauiXamlInflator>

        <!-- Display name -->
        <ApplicationTitle>Selvame</ApplicationTitle>

        <!-- App Identifier -->
        <ApplicationId>com.elevensource.reciclapp</ApplicationId>

        <!-- Versions -->
        <ApplicationDisplayVersion>1.0.0</ApplicationDisplayVersion>
        <ApplicationVersion>2026081301</ApplicationVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">26.0</SupportedOSPlatformVersion>
    </PropertyGroup>

    <ItemGroup>
        <!-- App Icon -->
        <MauiIcon Include="Resources\AppIcon\appicon.svg"/>

        <!-- Splash Screen -->
        <MauiSplashScreen Include="Resources\Splash\splash.svg" 
                          Color="#faf0d7" 
                          BaseSize="128,128" 
                          Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'ios'" />

        <!-- Images -->
        <MauiImage Include="Resources\Images\*"/>

        <!-- Custom Fonts -->
        <MauiFont Include="Resources\Fonts\*"/>

        <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
        <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)"/>
    </ItemGroup>
    
    <!-- Splash for iOS -->
    <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
        <InterfaceDefinition Include="Resources\Splash\LaunchScreen.storyboard" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Maui" Version="15.0.0" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.90" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.11" />
        <PackageReference Include="sqlite-net-pcl" Version="1.11.285" />
    </ItemGroup>

</Project>
