<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0-android;net10.0-ios</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <RootNamespace>ReciclaMe</RootNamespace>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <MauiXamlInflator>SourceGen</MauiXamlInflator>

        <!-- Display name -->
        <ApplicationTitle>Selvame</ApplicationTitle>

        <!-- App Identifier -->
        <ApplicationId>com.elevensource.reciclapp</ApplicationId>

        <!-- Versions -->
        <ApplicationDisplayVersion>1.0.0</ApplicationDisplayVersion>
        <ApplicationVersion>2026091602</ApplicationVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">26.0</SupportedOSPlatformVersion>
    </PropertyGroup>

    <PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android' and '$(Configuration)' == 'Release'">
        <!-- Explicitly include android-arm alongside other required architectures -->
        <RuntimeIdentifiers>android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-ios' Or '$(TargetFramework)' == 'net10.0-ios'">
        <!-- Forces the linker to skip user/third-party assemblies and only strip SDK frameworks -->
        <MtouchLink>SdkOnly</MtouchLink>

        <!-- Required if ONNX utilizes Swift bindings internally -->
        <_EnableSwiftSupport>true</_EnableSwiftSupport>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-ios|AnyCPU'">
        <UseInterpreter>true</UseInterpreter>
        <CreatePackage>false</CreatePackage>
        <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
        <CodesignProvision>Automatic</CodesignProvision>
        <CodesignKey>iPhone Distribution</CodesignKey>
        <MtouchLink>SdkOnly</MtouchLink>
    </PropertyGroup>

    <ItemGroup>
        <!-- App Icon -->
        <MauiIcon Include="Resources\AppIcon\appicon.svg"/>

        <!-- Splash Screen -->
        <MauiSplashScreen Include="Resources\Splash\splash.svg" 
                          Color="#faf0d7" 
                          BaseSize="128,128" 
                          Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'ios'" />

        <!-- Images -->
        <MauiImage Include="Resources\Images\*"/>

        <!-- Custom Fonts -->
        <MauiFont Include="Resources\Fonts\*"/>

        <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
        <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)"/>
    </ItemGroup>
    
    <!-- Splash for iOS -->
    <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
        <InterfaceDefinition Include="Resources\Splash\LaunchScreen.storyboard" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Maui" Version="15.0.0" />
        <PackageReference Include="CommunityToolkit.Maui.Camera" Version="6.1.0" />
        <PackageReference Include="CommunityToolkit.Maui.Core" Version="15.0.1" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.90" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.11" />
        <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.29.0" />
        <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.29.0" />
        <PackageReference Include="SkiaSharp" Version="4.152.0" />
        <PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="4.152.0" />

        <PackageReference Include="Sentry.Maui" Version="6.10.0" />
        <PackageReference Include="sqlite-net-pcl" Version="1.11.285" />
    </ItemGroup>

</Project>
